<?php
$config = require __DIR__ . '/config.php';
function escape($value) { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
$apkAvailable = is_file(__DIR__ . '/downloads/vetrix.apk');
$androidUrl = $config['android_store_url'] ?: ($apkAvailable ? 'download.php' : '');
$iosUrl = $config['ios_store_url'];
$webUrl = $config['web_app_url'];
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#3569f4">
  <meta name="description" content="Meet Vetrix: connected veterinary clinic management and a companion app for pet owners. Appointments, pet records, and everyday care, together.">
  <title>Vetrix — A little closer to better care.</title>
  <link rel="icon" href="assets/mark.svg" type="image/svg+xml">
  <link rel="stylesheet" href="styles.css?v=2">
  <link rel="stylesheet" href="enhancements.css?v=3">
  <script src="script.js?v=2" defer></script>
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
<header class="header wrap">
  <a href="#" class="brand" aria-label="Vetrix home"><img src="assets/mark.svg" width="36" height="36" alt="">vetrix<span class="brand-dot">.</span></a>
  <button class="menu-toggle" aria-expanded="false" aria-controls="navigation" aria-label="Toggle navigation">☰</button>
  <nav id="navigation" aria-label="Main navigation"><a href="#platform">The platform</a><a href="#features">Why Vetrix</a><a href="#faq">FAQs</a></nav>
  <a class="button small header-cta" href="#download">Get the app <span aria-hidden="true">↗</span></a>
</header>
<main id="main">
<section class="hero wrap">
  <div class="hero-copy">
    <p class="eyebrow"><span class="status-dot"></span> CONNECTED CARE. HAPPIER PETS.</p>
    <h1>Big love.<br>Little paws.<br><em>Better care.</em></h1>
    <p class="intro">From the clinic to your pocket, Vetrix brings pet owners and veterinary teams closer. Less keeping track. More caring.</p>
    <div class="actions"><a class="button" href="#download">Get the Vetrix app <span aria-hidden="true">↗</span></a><a class="text-link" href="#platform">Explore the platform <span aria-hidden="true">→</span></a></div>
    <div class="hero-note"><span class="mini-paw" aria-hidden="true">♡</span><span>One connected system.<br><strong>For both sides of the care journey.</strong></span></div>
    <div class="hero-chips"><span>Web workspace</span><span>Android companion</span></div>
  </div>
  <div class="hero-art" aria-label="Vetrix mobile app and golden retriever mascot">
    <div class="art-top"><span>MADE FOR THEIR WELLBEING</span><span>✳</span></div>
    <div class="orbit orbit-one"></div><div class="orbit orbit-two"></div>
    <div class="pet-drawing"><img src="assets/vetrix-retriever.png" alt="A happy golden retriever raising a paw, wearing a blue collar" width="1024" height="1536" fetchpriority="high"></div>
    <div class="float-card record-card"><span class="icon-tile">✓</span><div><strong>A little peace of mind.</strong><span>Pet records, always within reach.</span></div></div>
    <button class="phone screenshot-phone" type="button" data-preview aria-label="Enlarge the Vetrix mobile app screenshot" aria-haspopup="dialog"><img src="assets/vetrix-mobile.jpeg" alt="Vetrix Client Pet Care Access mobile login screen" width="716" height="1600" fetchpriority="high"><span class="preview-hint">View the app <span aria-hidden="true">↗</span></span></button>
    <span class="art-caption">Their world. In good hands.</span><span class="preview-label">Actual mobile app screen</span>
  </div>
</section>
<div class="benefit-strip"><div class="wrap"><span>Thoughtfully connected, from nose to tail.</span><b>✳ &nbsp; Clinic management</b><b>♡ &nbsp; Pet parent companion</b><b>↗ &nbsp; One shared care journey</b></div></div>
<section class="section wrap" id="platform"><div class="section-heading"><div><p class="eyebrow">TWO EXPERIENCES. ONE VETRIX.</p><h2>On your desk.<br>By their side.</h2></div><p>Different roles, the same love for animals.<br>Meet the tools that bring everyone together.</p></div>
<div class="platform-grid"><article class="platform-card clinic-card"><div class="card-tag">01 / FOR VETERINARY TEAMS</div><h3>A calmer day at the clinic.</h3><p>Give your team a shared place to manage appointments, patient records, inventory, and everyday operations.</p><a class="text-link" href="<?= escape($webUrl) ?>">Open the web app <span>↗</span></a><div class="desktop-preview" aria-label="Illustrative clinic dashboard preview"><div class="browser-bar"><i></i><i></i><i></i><span>Vetrix · Clinic workspace</span></div><div class="dashboard"><aside><b>✳</b><span class="selected">Overview</span><span>Appointments</span><span>Pet records</span><span>Inventory</span></aside><div class="dashboard-body"><div class="dashboard-title"><b>Your clinic, at a glance</b><span>Today ↗</span></div><div class="stat-grid"><div><small>Appointments</small><b>12</b></div><div><small>Pet patients</small><b>48</b></div><div><small>Available vets</small><b>3</b></div></div><div class="chart-title">Today's appointments <span>View all →</span></div><div class="dash-row"><i class="avatar peach">B</i><b>Bailey<small>Wellness checkup</small></b><span>09:30 AM</span><em>Approved</em></div><div class="dash-row"><i class="avatar sage">L</i><b>Luna<small>Vaccination</small></b><span>10:00 AM</span><em>Approved</em></div></div></div><div class="demo-label">Illustrative dashboard · sample data</div></div></article>
<article class="platform-card owner-card"><div class="card-tag">02 / FOR PET PARENTS</div><h3>Their care. In your pocket.</h3><p>Request a visit, view your pets’ health records, and keep up with clinic updates wherever your day takes you.</p><a class="text-link" href="#download">Meet your companion app <span>↗</span></a><div class="owner-visual"><div class="care-ring">♡<span>ALL THE LITTLE THINGS,<br>TOGETHER.</span></div><div class="care-chip chip-one"><span>▦</span> Appointment requests</div><div class="care-chip chip-two"><span>✚</span> Medical records</div><div class="care-chip chip-three"><span>✓</span> Vaccination history</div></div></article></div></section>
<section class="features-section" id="features"><div class="wrap section"><p class="eyebrow">LESS ADMIN. MORE AFFECTION.</p><h2>Care feels better<br>when it comes together.</h2><div class="features-grid"><article><span class="feature-icon">▦</span><h3>Make room for every visit.</h3><p>Pet owners request appointments. Clinic teams review schedules and assign veterinarians in one workspace.</p></article><article><span class="feature-icon">♡</span><h3>Know their story.</h3><p>Keep pet profiles, medical records, and vaccination history connected, so the next visit starts with context.</p></article><article><span class="feature-icon">↗</span><h3>Keep the day moving.</h3><p>Bring inventory, point of sale, staff availability, and reports into the clinic’s everyday workflow.</p></article></div></div></section>
<section class="section wrap explorer" aria-labelledby="explore-title">
  <div class="section-heading"><div><p class="eyebrow">TAKE A LITTLE LOOK AROUND</p><h2 id="explore-title">A place for every<br>part of their care.</h2></div><p>Choose a feature to see how it fits into your day.</p></div>
  <div class="explorer-shell">
    <div class="feature-tabs" role="tablist" aria-label="Explore Vetrix features" aria-orientation="vertical">
      <button id="tab-visits" role="tab" aria-selected="true" aria-controls="panel-visits" tabindex="0"><span class="tab-icon">▦</span><span><b>Appointments</b><small>Make the next visit easier</small></span><span class="tab-arrow">↗</span></button>
      <button id="tab-records" role="tab" aria-selected="false" aria-controls="panel-records" tabindex="-1"><span class="tab-icon">♡</span><span><b>Pet health records</b><small>Their story, all together</small></span><span class="tab-arrow">↗</span></button>
      <button id="tab-clinic" role="tab" aria-selected="false" aria-controls="panel-clinic" tabindex="-1"><span class="tab-icon">✚</span><span><b>Clinic workspace</b><small>Keep your team connected</small></span><span class="tab-arrow">↗</span></button>
    </div>
    <div class="feature-panel" id="panel-visits" role="tabpanel" aria-labelledby="tab-visits" tabindex="0"><div class="panel-copy"><span class="panel-kicker">FROM YOUR PHONE TO YOUR CLINIC</span><h3>A visit starts with<br>a simple request.</h3><p>Choose your approved pet, tell the clinic what they need, and request a date. Your clinic reviews the request and confirms the schedule.</p><a class="text-link" href="#download">Get started with the app <span>→</span></a></div><div class="sample-card"><span class="sample-label">ILLUSTRATIVE WORKFLOW</span><div class="sample-pet"><span>B</span><div><b>Bailey’s next visit</b><small>Wellness checkup</small></div><span class="sample-heart">♡</span></div><ol class="sample-timeline"><li><span>1</span><div><b>Request a visit</b><small>Pet parent · Mobile app</small></div></li><li><span>2</span><div><b>Review the schedule</b><small>Clinic team · Web app</small></div></li><li><span>3</span><div><b>Get ready for care</b><small>Check the appointment status</small></div></li></ol></div></div>
    <div class="feature-panel" id="panel-records" role="tabpanel" aria-labelledby="tab-records" tabindex="0" hidden><div class="panel-copy"><span class="panel-kicker">A LITTLE MORE PEACE OF MIND</span><h3>Their history.<br>Close at hand.</h3><p>Find your pet’s profile, consultation records, and vaccination history in one place. Stay informed between clinic visits.</p><a class="text-link" href="#download">Keep their care close <span>→</span></a></div><div class="sample-card"><span class="sample-label">ILLUSTRATIVE RECORD CATEGORIES</span><div class="sample-pet"><span>B</span><div><b>Bailey’s care folder</b><small>Pet health information</small></div><span class="sample-heart">♡</span></div><div class="record-row"><span>♡</span><div><b>Pet profile</b><small>The details that make them unique</small></div></div><div class="record-row"><span>✚</span><div><b>Medical history</b><small>Records from clinic consultations</small></div></div><div class="record-row"><span>✓</span><div><b>Vaccination history</b><small>View recorded vaccinations</small></div></div></div></div>
    <div class="feature-panel" id="panel-clinic" role="tabpanel" aria-labelledby="tab-clinic" tabindex="0" hidden><div class="panel-copy"><span class="panel-kicker">FOR THE PEOPLE BEHIND THE CARE</span><h3>A shared workspace.<br>A smoother day.</h3><p>Support your clinic’s daily work with role-based access for administrators, veterinarians, and staff. Bring scheduling, patient records, inventory, and sales together.</p><a class="text-link" href="<?= escape($webUrl) ?>">Open the clinic workspace <span>↗</span></a></div><div class="sample-card"><span class="sample-label">CLINIC TEAM WORKFLOWS</span><div class="workspace-heading"><img src="assets/mark.svg" width="30" height="30" alt=""><b>One team. Connected.</b></div><div class="record-row"><span>A</span><div><b>Administrators</b><small>Manage operations and reports</small></div></div><div class="record-row"><span>V</span><div><b>Veterinarians</b><small>Consultations and health records</small></div></div><div class="record-row"><span>S</span><div><b>Clinic staff</b><small>Appointments, inventory, and sales</small></div></div></div></div>
  </div>
</section>
<section class="section wrap journey"><div><p class="eyebrow">A SIMPLE START</p><h2>Good care starts<br>with a connection.</h2><p class="muted">Your clinic and your pet’s next chapter,<br>a little closer together.</p></div><ol class="steps"><li><span>01</span><div><h3>Get the Vetrix app</h3><p>Download the available mobile release to your phone.</p></div></li><li><span>02</span><div><h3>Connect with your clinic</h3><p>Register your account, complete clinic approval and email verification, and access your pet profiles.</p></div></li><li><span>03</span><div><h3>Stay close to their care</h3><p>Request appointments for approved pets, check records, and read clinic notifications.</p></div></li></ol></section>
<section class="wrap" id="download"><div class="download-panel"><div><p class="eyebrow">YOUR NEXT CHAPTER OF PET CARE</p><h2>For the love<br>of little paws.</h2><p>Take Vetrix with you. Their care belongs close.</p><div class="download-actions">
<?php if ($androidUrl): ?><a class="button light" href="<?= escape($androidUrl) ?>">↓ &nbsp; <?= $config['android_store_url'] ? 'Get it on Google Play' : 'Download for Android' ?></a><?php else: ?><span class="button unavailable" aria-disabled="true">Android · Coming soon</span><?php endif; ?>
<?php if ($iosUrl): ?><a class="button light" href="<?= escape($iosUrl) ?>">Get it on the App Store ↗</a><?php endif; ?>
</div></div></div></section>
<section class="section wrap faq" id="faq"><div><p class="eyebrow">A FEW THINGS TO KNOW</p><h2>Curious?<br>We’re here for it.</h2></div><div class="faq-list"><details><summary>What is Vetrix?<span>+</span></summary><p>Vetrix is a veterinary clinic management and monitoring system. The web app supports clinic teams, while the companion mobile app helps pet owners access their pet information and request care.</p></details><details><summary>Who uses the web app and mobile app?<span>+</span></summary><p>Administrators, veterinarians, and clinic staff use the web app with role-based access. Pet owners use the mobile app for their own pets, appointments, records, and notifications.</p></details><details><summary>How do I download the app?<span>+</span></summary><p>Visit the download section on your phone. When a release is available, use the Android download or store button. For a direct Android APK, open the downloaded file and follow Android’s installation prompts. Direct APK installation is only for Android; iPhones require an available App Store release.</p></details><details><summary>Can I book an appointment right away?<span>+</span></summary><p>Your client account must be approved by the clinic and verified by email. Once your pet is approved, you can request an appointment. The clinic reviews requests and confirms scheduling.</p></details><details><summary>Do the apps need an internet connection?<span>+</span></summary><p>Yes. An internet connection is needed to access the clinic system and retrieve current appointments, records, and updates.</p></details></div></section>
</main>
<footer class="wrap"><a href="#" class="brand"><img src="assets/mark.svg" width="30" height="30" alt="">vetrix.</a><p>Better connected. Better cared for.</p><span>© <?= date('Y') ?> Vetrix</span><a href="#main">Back to top ↑</a></footer>
<dialog class="app-dialog" aria-labelledby="app-preview-title"><div class="dialog-header"><div><span class="panel-kicker">MEET YOUR MOBILE COMPANION</span><h2 id="app-preview-title">A closer look at Vetrix.</h2></div><button type="button" class="dialog-close" aria-label="Close app preview">×</button></div><div class="dialog-body"><img src="assets/vetrix-mobile.jpeg" alt="Full screenshot of the Vetrix mobile app login page" width="716" height="1600" loading="lazy"><div class="dialog-copy"><img src="assets/mark.svg" alt="" width="46" height="46"><h3>Their care,<br>wherever you are.</h3><p>Your pet-owner companion for appointments, health records, and clinic updates.</p><p class="screenshot-note">This is a preview of the mobile app. Download Vetrix to sign in or create an account.</p><a href="#download" class="button" data-close-preview>Get the Android app ↗</a></div></div></dialog>
</body></html>
